### ISSUE TITLE
Settings Icons Not Displaying

### ISSUE THREAD

**Issue by NorthernLights** [NortheBridge/skin.arctic.zephyr.fromashes#50]
Icons for Settings using wrong path in _**Arctic Zephyr: From Ashes Danvers Preview (Alpha 2)**_.

Should be media://<path> and not special://<path>

**Comment by NorthernLights** [comment]
Issue resolved with Patch #49

**Comment by ericzinnikas** [comment]
I think I'm still having this problem... or I'm missing something obvious.  I've only got "Movies" and "TV Shows" buttons on the home screen, no other options/menus.  I've poked at it for a while and cannot figure out how to get into any of the Settings menus.

![image](https://cloud.githubusercontent.com/assets/3394214/23115673/4746a574-f6fb-11e6-89b5-97a499dd58dc.jpg)

**Comment by NorthernLights** [comment]
@ericzinnikas And this is on Beta 10? If so, that's really odd. One thing you can try doing is to delete the GUI settings from %AppData%\Kodi (or equivalent) and trying again. Or reloading the skin. We'll note it on the updated project tracker when it releases soon.

**Comment by ericzinnikas** [comment]
Yeah, I installed directly from the repository.  I can try using the zip from the Github release too.  Will test more later today with a fresh guisettings.xml.

**Comment by ericzinnikas** [comment]
Installing the zip from Github and resetting the UI seems to have fixed this! I do have another issue though... when "TV Shows" is hovered over, it shows the "Movie Spotlight" and when "Movies" are hovered over, it shows "Resumable Movies", or just black if I haven't recently watched anything.  Any way to modify this behavior?

Also let me know if we should discuss this in a separate issue or somewhere else (IRC).
